kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: splatoon-chatops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splatoon-chatops
  template:
    metadata:
      labels:
        app: splatoon-chatops
    spec:
      containers:
        - name: splatoon-chatops
          image: docker.io/sayyeah-t/splatoon-chatops:arm-latest
          imagePullPolicy: Always
          volumeMounts:
            - name: splatoon-chatops-conf
              mountPath: /etc/take2-chatops
      volumes:
        - name: splatoon-chatops-conf
          configMap:
            name: splatoon-chatops-conf
